version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-vue-js}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        NODE_VERSION: ${NODE_VERSION:-18.18.0}
        LOCALE: ${LOCALE:-ja_JP.UTF-8}
    tty: true
    environment:
      TZ: ${TIME_ZONE:-Asia/Tokyo}
      GIT_USER: ${GIT_USER:-user}
      GIT_EMAIL: ${GIT_EMAIL:-email}
    volumes:
      - ../:/home/${USER_NAME:-vscode}/workspace:cached
    ports:
      - ${WORKSPACE_PORT:-9999}:9999

